# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{linkedin}
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland"]
  s.date = %q{2011-02-01}
  s.description = %q{Ruby wrapper for the LinkedIn API}
  s.email = %q{wynn.netherland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/linked_in/api_standard_profile_request.rb",
    "lib/linked_in/base.rb",
    "lib/linked_in/birthdate.rb",
    "lib/linked_in/client.rb",
    "lib/linked_in/company.rb",
    "lib/linked_in/connections.rb",
    "lib/linked_in/country.rb",
    "lib/linked_in/education.rb",
    "lib/linked_in/error.rb",
    "lib/linked_in/group.rb",
    "lib/linked_in/location.rb",
    "lib/linked_in/message.rb",
    "lib/linked_in/network.rb",
    "lib/linked_in/paginator.rb",
    "lib/linked_in/people.rb",
    "lib/linked_in/person.rb",
    "lib/linked_in/position.rb",
    "lib/linked_in/profile.rb",
    "lib/linked_in/recipient.rb",
    "lib/linked_in/recipients.rb",
    "lib/linked_in/update.rb",
    "lib/linked_in/url_resource.rb",
    "lib/linkedin.rb",
    "spec/client_spec.rb",
    "spec/fixtures/blank.xml",
    "spec/fixtures/connections.xml",
    "spec/fixtures/error.xml",
    "spec/fixtures/mailbox_items.xml",
    "spec/fixtures/network_status_with_group.xml",
    "spec/fixtures/network_statuses.xml",
    "spec/fixtures/people-page1.xml",
    "spec/fixtures/people-page2.xml",
    "spec/fixtures/picture_updates.xml",
    "spec/fixtures/profile.xml",
    "spec/fixtures/profile_full.xml",
    "spec/fixtures/profile_with_positions.xml",
    "spec/fixtures/search.xml",
    "spec/fixtures/status.xml",
    "spec/linked_in/paginator_spec.rb",
    "spec/oauth_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/pengwynn/linkedin}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby wrapper for the LinkedIn API}
  s.test_files = [
    "examples/authenticate.rb",
    "examples/network.rb",
    "examples/profile.rb",
    "examples/status.rb",
    "spec/client_spec.rb",
    "spec/linked_in/paginator_spec.rb",
    "spec/oauth_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth>, ["~> 0.3.5"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<crack>, [">= 0.1.4"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_runtime_dependency(%q<oauth>, ["~> 0.3.5"])
      s.add_runtime_dependency(%q<crack>, ["~> 0.1.4"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.1"])
      s.add_development_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.4"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.5"])
    else
      s.add_dependency(%q<oauth>, ["~> 0.3.5"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<crack>, [">= 0.1.4"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<oauth>, ["~> 0.3.5"])
      s.add_dependency(%q<crack>, ["~> 0.1.4"])
      s.add_dependency(%q<shoulda>, [">= 2.10.1"])
      s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_dependency(%q<mocha>, [">= 0.9.4"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
    end
  else
    s.add_dependency(%q<oauth>, ["~> 0.3.5"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<crack>, [">= 0.1.4"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<oauth>, ["~> 0.3.5"])
    s.add_dependency(%q<crack>, ["~> 0.1.4"])
    s.add_dependency(%q<shoulda>, [">= 2.10.1"])
    s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
    s.add_dependency(%q<mocha>, [">= 0.9.4"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
  end
end

